name: Build Kodi Repository

on:
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Kodi Repo
        uses: xbmc/action-kodi-repo-generator@v1
