name: Build Kodi Repository

on:
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v4

      - name: Checkout LegendasDivX Addon Code
        uses: actions/checkout@v4
        with:
          repository: 'rdscorreia74/service.subtitles.legendasdivx' # <-- Change this to your addon's repo name
          ref: 'Matrix'
          path: 'service.subtitles.legendasdivx'

      - name: Generate Kodi Repo Files
        run: |
          mkdir -p public/service.subtitles.legendasdivx
          mkdir -p public/repository.rdscKodiRepo
          
          # Zip the LegendasDivX addon
          cd service.subtitles.legendasdivx
          zip -r ../public/service.subtitles.legendasdivx/service.subtitles.legendasdivx-1.0.7.zip . -x "*.git*"
          cd ..

          # Zip the repository addon
          cd repository.rdscKodiRepo
          zip -r repository.rdscKodiRepo-1.0.0.zip repository.rdscKodiRepo/
          cd ..

          # Build addons.xml
          echo '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' > public/addons.xml
          echo '<addons>' >> public/addons.xml
          sed '/<?xml/d' repository.rdscKodiRepo/addon.xml >> public/addons.xml
          sed '/<?xml/d' service.subtitles.legendasdivx/addon.xml >> public/addons.xml
          echo '</addons>' >> public/addons.xml

          # Copy repository zip to root so Kodi and web root can access it directly
          cp public/repository.rdscKodiRepo/repository.rdscKodiRepo-1.0.0.zip public/
          cp index.html public/index.html
          
          # Generate Hash
          cd public
          md5sum addons.xml | cut -d ' ' -f 1 > addons.xml.md5

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
